### ISSUE TITLE
Shaping

### ISSUE THREAD

**Issue by davelab6** [Gue3bara/Lemonada-Arabic#10]
I think there is a problem with the spacing, where some letters are not joining 

<img width="394" alt="screen shot 2016-05-28 at 10 35 16" src="https://cloud.githubusercontent.com/assets/261579/15627888/abd7913c-24c0-11e6-9495-02bfca24ac85.png">

**Comment by Gue3bara** [comment]
the connecting letters issue i already fixed it yesterday 
the qaaf and saad touching isnt this line spacing issue?

**Comment by davelab6** [comment]
> the qaaf and saad touching isnt this line spacing issue?

Its a vertical metrics issue, I think.

**Comment by Gue3bara** [comment]
@davelab6 im on it and will update you in a bit

**Comment by davelab6** [comment]
@Gue3bara any news?

**Comment by davelab6** [comment]
Fixed in latest release
