### ISSUE TITLE
Bad MM glyphs

### ISSUE THREAD

**Issue by m4rc1e** [Gue3bara/Lemonada-Arabic#11]
uni2206, uni0394:
![screen shot 2017-08-03 at 17 41 41](https://user-images.githubusercontent.com/7525512/28932917-114977c2-7873-11e7-9875-cfb7e9e7e104.png)

uni25cc:
![screen shot 2017-08-03 at 17 42 55](https://user-images.githubusercontent.com/7525512/28932948-381efa34-7873-11e7-8f03-800b652d95e8.png)

**Comment by Gue3bara** [comment]
Fixed
<img width="502" alt="screenshot 2017-08-03 22 13 57" src="https://user-images.githubusercontent.com/12478169/28941948-e4855f68-7899-11e7-8562-d65a74dace88.png">
<img width="392" alt="screenshot 2017-08-03 22 19 36" src="https://user-images.githubusercontent.com/12478169/28941949-e4cb4712-7899-11e7-855a-7b53945c0398.png">
