### ISSUE TITLE
U+0658 ARABIC MARK NOON GHUNNA does not look right

### ISSUE THREAD

**Issue by khaledhosny** [Gue3bara/Lemonada-Arabic#14]
The current glyph looks like a small lam, however it should be crescent-like, compare Lemonada glyph with Amiri and Noto Naskh Arabic glyphs (ignore the dotted circle):
![lemonada](https://user-images.githubusercontent.com/93914/34458297-2e533fc4-edd5-11e7-85e5-38fa412c174e.png) ![amiri](https://user-images.githubusercontent.com/93914/34458246-8da977e2-edd3-11e7-89a7-f878a12fea76.png)![noto](https://user-images.githubusercontent.com/93914/34458257-e597580c-edd3-11e7-8d78-f2a0ce55feea.png)

**Comment by Gue3bara** [comment]
Updated the design according to [the conversation we had over the noon ghunna in Cairo](https://github.com/Gue3bara/Cairo/issues/22#issue-285232519)
<img width="627" alt="screenshot 2018-01-02 23 32 07" src="https://user-images.githubusercontent.com/12478169/34500944-812b60fe-f015-11e7-8ebf-fb466002d647.png">

**Comment by khaledhosny** [comment]
Looks good, thanks.
