### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by alexmyczko** [Gue3bara/Lemonada-Arabic#17]
Hi !

Awesome work on the fonts !

Can you make a "release" on github to ease the download for the non "github-aware" people interested on this work ?

Thanks !

**Comment by Gue3bara** [comment]
Sure i will do that

**Comment by alexmyczko** [comment]
You might want to give a hint how you build it? I'm with this command:
`fontmake -i -o otf -g sources/*.glyphs`

**Comment by Gue3bara** [comment]
Done
