### ISSUE TITLE
Add Regular, Medium and SemiBold instances?

### ISSUE THREAD

**Issue by davelab6** [Gue3bara/Lemonada-Arabic#2]
Since there is a Light and Bold master, why not add Regular, Medium and SemiBold instances?

www.impallari.com/familysteps/ helps to calculate their values

**Comment by Gue3bara** [comment]
planing to start working on that by end of March after i have the 1st beta of the current naskh project i am working on so not to lose focus on it at this early stage

**Comment by davelab6** [comment]
A 400 is **required** for the font to be onboarded, so I'll need to fix this up myself in the next few days... are the masters interpolatable?

**Comment by Gue3bara** [comment]
Masters are interpolatable and as this is required like that then leave it for me and i will get this done before the weekend 
Will update you again today with the progress and if thwre is any issues

**Comment by Gue3bara** [comment]
I worked on it and found some compatibility issues and fixed 90% of them 
will generate Light, regular, semi bold & bold within 24 hours 
the same will be done for Cairo & El-Messiri by the end of the week

**Comment by davelab6** [comment]
Awesome!

**Comment by Gue3bara** [comment]
@davelab6 
I fixed most of the compatibility issues but with these 8 glyphs i cant seem to know what's wrong with them 
Glyphs is saying there's a problem with the glyph without showing any problem with the curves or the anchors all green and compatible but still cant interpolate the glyphs

U+FE94
U+FEE0
dotless qaf
hehgoalHamzaabove-ar.fina
U+FEC0
U+FEBF
U+0686
U+FB7B

https://www.dropbox.com/s/7c7ss6k67qtx0ex/Screenshot%202016-03-02%2004.03.28.png?dl=0
https://www.dropbox.com/s/akls210yljff7js/Screenshot%202016-03-02%2004.04.15.png?dl=0
https://www.dropbox.com/s/f1y5rlqtgem3a29/Screenshot%202016-03-02%2004.04.48.png?dl=0

can you take a look and let me know what you think ?

**Comment by davelab6** [comment]
I believe it is because (a) the contour/component orders are not the same and (b) one master has a contour for a shape while the other has a component for a shape and the component's parent contour is not compatible with the other contour.

<img width="1680" alt="screen shot 2016-03-01 at 22 31 42" src="https://cloud.githubusercontent.com/assets/261579/13449918/cf656f78-dffd-11e5-9eee-9e34fc75a5ff.png">

In the above you can see that the two dots are first in one master and second in the other, because the blue line is going up and to the right, and when you go to Filter, Fix Compatibility, the order is not the same.

**Comment by davelab6** [comment]
Also I see that while U+FE94 is not working, but U+FEEA is

**Comment by davelab6** [comment]
AHA, it is stray points!

**Comment by davelab6** [comment]
Hmm might not be. Paths > Tidy Up Paths (Cmd-Opt-Shift-T) can help with that btw. cf. https://glyphsapp.com/tutorials/drawing-good-paths

See in the image above, in the Fix Compatibility window, on the right col, there is 3 rows, not 2. I thought initially that the top row is to indicate its a composite or something, but actually there are 2 'stray' points in the output. 

But when I revert the file I can't find them again. I keep looking.

**Comment by davelab6** [comment]
Hmm, I filed https://forum.glyphsapp.com/t/why-cant-i-decompose-this-glyph/3997

**Comment by davelab6** [comment]
HAH. This little command fixes it, without making further changes:

<img width="1680" alt="screen shot 2016-03-02 at 00 55 29" src="https://cloud.githubusercontent.com/assets/261579/13451956/951ddbfc-e011-11e5-912e-ea3095be7331.png">

**Comment by davelab6** [comment]
The 'reinterpolate' also works on:
- dotlessqaf-ar.init
- hehgoalHamzaabove-ar.fina
- U+FEC0
- U+FEBF

But for these 3, it 'fixes' them by making them the same in both Light and Bold masters! Hmm.
- U+FEE0
- U+0686
- U+FB7B

Also, after going over your list above, this Smart Filter shows:

<img width="1270" alt="screen shot 2016-03-02 at 01 01 00" src="https://cloud.githubusercontent.com/assets/261579/13452038/49d49252-e012-11e5-8089-919b6c17a4d3.png">

**Comment by davelab6** [comment]
Okay. I have a clean copy of this repo, to be sure clean as I run

```
git reset --hard;
```

Then I open the  Lemonada-Arabic.glyphs  file in the very latest version `Version 2.3b (854)` which is installed this way,

<img width="440" alt="screen shot 2016-02-29 at 09 11 39" src="https://cloud.githubusercontent.com/assets/261579/13452502/5e62c6fe-e016-11e5-8dea-ea9454245559.png">

Then I go to `tehMarbuta-ar.fina` and I see this:

<img width="1680" alt="screen shot 2016-03-02 at 01 31 11" src="https://cloud.githubusercontent.com/assets/261579/13452509/76a7ef96-e016-11e5-90db-6b210c7f0516.png">

Then I go to Glyphs, Preferences, User Settings, and **untick** master compatibility. 

Then I go to the Bold layer, and I see this:

<img width="1680" alt="screen shot 2016-03-02 at 01 31 56" src="https://cloud.githubusercontent.com/assets/261579/13452521/918ab9f6-e016-11e5-9816-05c6be7a277e.png">

There is that stray point I found earlier! I just click it once, 

<img width="1680" alt="screen shot 2016-03-02 at 01 32 18" src="https://cloud.githubusercontent.com/assets/261579/13452531/ab64ca7e-e016-11e5-86d3-b1964052870d.png">

hit the backspace key to delete it, and then reinterpolate and the glyphs are all looking good:

<img width="1680" alt="screen shot 2016-03-02 at 01 32 33" src="https://cloud.githubusercontent.com/assets/261579/13452535/b7d2ea34-e016-11e5-8b23-1d797f067982.png">

**Comment by davelab6** [comment]
That leaves these three: چ ﭻ ﻠ

<img width="1680" alt="screen shot 2016-03-02 at 01 34 12" src="https://cloud.githubusercontent.com/assets/261579/13452560/e10b9108-e016-11e5-90e1-7cdbfa763df6.png">

I think https://github.com/mekkablue/FixZeroHandles can help.

**Comment by davelab6** [comment]
I filed https://forum.glyphsapp.com/t/how-to-find-out-what-the-interpolation-error-shown-is/3998 too

**Comment by davelab6** [comment]
Nico says

> Lemonada's tcheh-ar has a extra anchor (center at x = 509, y = -104) in Light Italic.

**Comment by Gue3bara** [comment]
I was able to fix all the issues reported here but the issue with لـ 
the fix zero handles didnt help and i am rechecking the whole glyph over again

**Comment by Gue3bara** [comment]
it was a problem with the entry anchor and now it's fixed
