### ISSUE TITLE
Contour improvements

### ISSUE THREAD

**Issue by davelab6** [Gue3bara/Lemonada-Arabic#4]
<img width="1117" alt="screen shot 2016-03-01 at 22 59 51" src="https://cloud.githubusercontent.com/assets/261579/13450516/419a5dbe-e004-11e5-9066-567dec94d51d.png">

This point (in blue) should have a control point coming out of it, but does not. 

I think this script can show you such glyphs:

https://github.com/mekkablue/Glyphs-Scripts/blob/master/Paths/New%20Tab%20with%20Path%20Problems.py

**Comment by davelab6** [comment]
Yes, it says

Zero Handles:

```
چچﭻﭻحﺢﺢﺤﺣﺣدﺪسسﺲﺲصصﺺﺺﺼﺼﺻﺻططﻂﻂﻄﻄﻃﻃععﻊﻊﻌﻌﻋﻋڡڡ/dotlessfeh-ar.fina/dotlessfeh-ar.fina/dotlessfeh-ar.medi/dotlessfeh-ar.medi/dotlessfeh-ar.init/dotlessfeh-ar.init ٯٯ/dotlessqaf-ar.fina/dotlessqaf-ar.fina ﻜﻜﻛﻛککﮏﮏللﻞﻞﻠﻠممﻢﻢﻤﻤﻣﻣںںﮟﮟههﻪﻪﻬﻬﻫﻫﮧﮧﮩﮩھھﮫﮫووﻮﻮىﻰےےﮯﮯ١٢٥٦٩٩۴/four-persian.urdu ۵۵/seven-persian.urdu ∆∞ؕؕ/wasla-ar/wasla-ar ٕٔ/hamzacenter-ar ٌٌُُّّ٘٘
```

Outline Order and Orientation:

```
صصﺼﺼﺻﺻططممﻣﻣههﻫﻫ/hehgoalHamzaabove-ar.fina ﺔ00/zero.numr/zero.numr ……--¤¤©©®®℮℮̣̣̇̇̊̊̃̃
```

**Comment by Gue3bara** [comment]
<img width="417" alt="screenshot 2016-03-03 00 55 31" src="https://cloud.githubusercontent.com/assets/12478169/13478649/aa9a6f1c-e0da-11e5-8730-af4c45b52f69.png">
Hurrah!
