### ISSUE TITLE
Minor things

### ISSUE THREAD

**Issue by davelab6** [Gue3bara/Lemonada-Arabic#6]
In Font Info, Font
- [x] Add a fsType and set it to Not Set, which appears as installable

<img width="685" alt="screen shot 2016-03-02 at 01 53 22" src="https://cloud.githubusercontent.com/assets/261579/13452835/9443905c-e019-11e5-96f1-a73718524e9e.png">
- [x] Change copyright notice to
  
  Copyright 2015 The Lemonada Project Authors. 

Then add the AUTHORS and the other 2 files as per https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md

In Font Info, Masters
- [x] Set both masters' italic angles to zero

In Font Info, Instances
- [x] Inside SemiBold, remove space from the style name `Semi Bold` to `SemiBold`
- [x] Inside Bold, tick Style Linking

<img width="681" alt="screen shot 2016-03-02 at 01 56 01" src="https://cloud.githubusercontent.com/assets/261579/13452882/f8ac73d8-e019-11e5-8c82-16046edc42e3.png">

**Comment by Gue3bara** [comment]
DONE
Thank you Dave so much for your time and help
Thank you man :)

**Comment by Gue3bara** [comment]
why do we set italic angel to zero?
this value was set by Eduardo btw and now if i apply this the whole kerning is messed up

**Comment by davelab6** [comment]
It should not effect the kerning... 

We do not set it because the fonts are presented to the system as upright/romans, not italics; for them to be italics, they need to have 'real' upright/romans which don't exist.

cc @etunni

**Comment by davelab6** [comment]
For italic angle, you can set it to zero as an instance custom parameter:

<img width="680" alt="screen shot 2016-03-02 at 16 48 15" src="https://cloud.githubusercontent.com/assets/261579/13476614/a38f3e76-e096-11e5-9ddd-c28de0eb00f7.png">

**Comment by Gue3bara** [comment]
and keeping it 9 as it was in the masters, right?

**Comment by davelab6** [comment]
No, it must be zero because these fonts are presented to the system as roman/upright styles.

**Comment by Gue3bara** [comment]
but this way i still have the same issue 
fixed masters angel to 0 
<img width="725" alt="screenshot 2016-03-03 00 02 46" src="https://cloud.githubusercontent.com/assets/12478169/13477114/8714e5f6-e0d3-11e5-8294-9080f6d8b0da.png">
added the custom parameter for all instanced set to 0 
<img width="723" alt="screenshot 2016-03-03 00 04 58" src="https://cloud.githubusercontent.com/assets/12478169/13477137/9d34277a-e0d3-11e5-8659-e52165bcda41.png">
so i end up with the same result 
<img width="262" alt="screenshot 2016-03-03 00 05 41" src="https://cloud.githubusercontent.com/assets/12478169/13477167/b60561ba-e0d3-11e5-86b7-322886fa284b.png">

**Comment by davelab6** [comment]
oh I see. sorry, you can set the angle in the Metrics area back how it was,
and leave the customParameter value at 0.0

**Comment by Gue3bara** [comment]
great 
now it's working perfect
